import { PaperStyle, JournalFontFamily, ScrapbookElement, ScrapbookLayout } from "../types";

export interface PaperStyleMeta {
  id: PaperStyle;
  label: string;
  icon: string;
  bgClass: string;
  defaultBgColor: string;
  description: string;
  cssStyle?: React.CSSProperties;
}

export const PAPER_STYLES: PaperStyleMeta[] = [
  {
    id: "cream_linen",
    label: "Cream Linen",
    icon: "📜",
    bgClass: "bg-[#FAF7F2] text-stone-900",
    defaultBgColor: "#FAF7F2",
    description: "Warm, timeless artisan stationery with a soft natural texture.",
  },
  {
    id: "ruled_notebook",
    label: "Ruled Notebook",
    icon: "📓",
    bgClass: "bg-[#FDFCF7] text-stone-900",
    defaultBgColor: "#FDFCF7",
    description: "Classic college-ruled journal with subtle blue guidelines & red margin.",
  },
  {
    id: "dot_grid",
    label: "Dot Grid",
    icon: "📐",
    bgClass: "bg-[#F8F7F4] text-stone-900",
    defaultBgColor: "#F8F7F4",
    description: "Architectural bullet journal dot-matrix for structured scrapbooking.",
  },
  {
    id: "kraft_paper",
    label: "Kraft Paper",
    icon: "📦",
    bgClass: "bg-[#EADBCA] text-stone-950",
    defaultBgColor: "#EADBCA",
    description: "Warm vintage recycled parcel craft paper with organic charm.",
  },
  {
    id: "soft_rose",
    label: "Soft Pastel",
    icon: "🌸",
    bgClass: "bg-[#FFF4F6] text-stone-900",
    defaultBgColor: "#FFF4F6",
    description: "Delicate blush tinted paper for heartfelt, intimate reflections.",
  },
  {
    id: "vintage_parchment",
    label: "Vintage Parchment",
    icon: "📜",
    bgClass: "bg-[#F5EFE0] text-amber-950",
    defaultBgColor: "#F5EFE0",
    description: "Aged antiquarian manuscript paper with warm sepia undertones.",
  },
  {
    id: "sage_meadow",
    label: "Sage Meadow",
    icon: "🌿",
    bgClass: "bg-[#F0F5F1] text-emerald-950",
    defaultBgColor: "#F0F5F1",
    description: "Calm botanical soft green paper evocative of spring leaves.",
  },
  {
    id: "midnight_journal",
    label: "Midnight Ink",
    icon: "🌑",
    bgClass: "bg-[#1E1F24] text-stone-100",
    defaultBgColor: "#1E1F24",
    description: "Deep nocturnal dark paper with starry gold & chalk accents.",
  },
];

export const JOURNAL_FONTS: { id: JournalFontFamily; label: string; preview: string; cssFamily: string }[] = [
  {
    id: "Newsreader",
    label: "Newsreader (Editorial Serif)",
    preview: "Reflective and timeless",
    cssFamily: "'Newsreader', Georgia, serif",
  },
  {
    id: "Kalam",
    label: "Kalam (Casual Handwriting)",
    preview: "Personal handwritten thoughts",
    cssFamily: "'Kalam', cursive",
  },
  {
    id: "Caveat",
    label: "Caveat (Expressive Script)",
    preview: "Fluid handwritten diary entry",
    cssFamily: "'Caveat', cursive",
  },
  {
    id: "Courier Prime",
    label: "Courier Prime (Vintage Typewriter)",
    preview: "Mechanical typewriter aesthetic",
    cssFamily: "'Courier Prime', monospace",
  },
  {
    id: "Playfair Display",
    label: "Playfair Display (Literary Classic)",
    preview: "Elegant bookcraft titles",
    cssFamily: "'Playfair Display', serif",
  },
  {
    id: "Plus Jakarta Sans",
    label: "Plus Jakarta (Clean Modern)",
    preview: "Minimal modern clarity",
    cssFamily: "'Plus Jakarta Sans', sans-serif",
  },
];

export const WASHI_TAPE_COLORS = [
  { id: "amber", name: "Amber Ochre", bg: "bg-amber-300/80 border-amber-400" },
  { id: "rose", name: "Blush Rose", bg: "bg-rose-300/80 border-rose-400" },
  { id: "sage", name: "Sage Mint", bg: "bg-emerald-300/80 border-emerald-400" },
  { id: "cyan", name: "Sky Cyan", bg: "bg-cyan-300/80 border-cyan-400" },
  { id: "lavender", name: "Soft Lavender", bg: "bg-purple-300/80 border-purple-400" },
  { id: "kraft", name: "Kraft Brown", bg: "bg-[#c8ad8d]/85 border-[#b69976]" },
];

export const STICKER_PACKS = [
  {
    category: "Mindful & Nature",
    stickers: ["🌿", "🌸", "🌱", "🍃", "☕", "🕯️", "🌞", "🌙", "✨", "🦋"],
  },
  {
    category: "Scrapbook & Diary",
    stickers: ["📌", "🏷️", "💌", "📖", "🎨", "⭐", "💫", "💖", "🕊️", "🔑"],
  },
  {
    category: "Emotions & Memory",
    stickers: ["😊", "💭", "🔥", "🌈", "💎", "🎯", "📸", "🍵", "🌻", "🎈"],
  },
];

export interface JournalTemplate {
  id: string;
  name: string;
  badge: string;
  description: string;
  paperStyle: PaperStyle;
  paperColor: string;
  fontFamily: JournalFontFamily;
  generateElements: (title: string, date: string, text: string, aiSummary?: string) => ScrapbookElement[];
}

export const JOURNAL_TEMPLATES: JournalTemplate[] = [
  {
    id: "minimal_paper",
    name: "Minimal Paper",
    badge: "📄",
    description: "Clean cream stationery with refined typography and pencil rules.",
    paperStyle: "cream_linen",
    paperColor: "#FAF7F2",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_top",
        type: "tape",
        x: 320,
        y: 12,
        width: 140,
        height: 28,
        rotation: -1,
        zIndex: 5,
        tapeColor: "bg-amber-200/80 border-amber-300",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 260,
        height: 35,
        rotation: 0,
        zIndex: 10,
        content: `🗓️ ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#78716c",
        textAlign: "left",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 90,
        width: 660,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Reflective Journal",
        fontFamily: "Playfair Display",
        fontSize: 30,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#1c1917",
        textAlign: "left",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 165,
        width: 660,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Write your authentic reflections here... Notice the sensations, emotions, and thoughts moving through your day.",
        fontFamily: "Newsreader",
        fontSize: 17,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#292524",
        textAlign: "left",
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 580,
              width: 660,
              height: 140,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Reflection Insight",
              backgroundColor: "#fef3c7",
              borderColor: "#fde68a",
              color: "#78350f",
            },
          ]
        : []),
      {
        id: "decor_leaf",
        type: "sticker",
        x: 690,
        y: 45,
        width: 50,
        height: 50,
        rotation: 12,
        zIndex: 15,
        content: "🌿",
        fontSize: 32,
      },
    ],
  },
  {
    id: "soft_pastel",
    name: "Soft Pastel",
    badge: "🌸",
    description: "Dreamy blush pink with expressive handwriting and sweet stickers.",
    paperStyle: "soft_rose",
    paperColor: "#FFF4F6",
    fontFamily: "Caveat",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_corner_1",
        type: "tape",
        x: 40,
        y: 20,
        width: 120,
        height: 26,
        rotation: -8,
        zIndex: 5,
        tapeColor: "bg-rose-300/80 border-rose-400",
      },
      {
        id: "tape_corner_2",
        type: "tape",
        x: 620,
        y: 25,
        width: 110,
        height: 26,
        rotation: 10,
        zIndex: 5,
        tapeColor: "bg-purple-300/80 border-purple-400",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 80,
        width: 660,
        height: 65,
        rotation: -1,
        zIndex: 10,
        content: title || "A gentle check-in with my heart",
        fontFamily: "Kalam",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "normal",
        color: "#831843",
        textAlign: "left",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 220,
        height: 30,
        rotation: 2,
        zIndex: 10,
        content: `🌸 ${date}`,
        fontFamily: "Caveat",
        fontSize: 18,
        color: "#9d174d",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 160,
        width: 660,
        height: 360,
        rotation: 0,
        zIndex: 10,
        content: text || "Pour your heart out gently onto the page. There are no right or wrong words here, just honest feelings.",
        fontFamily: "Caveat",
        fontSize: 22,
        fontWeight: "normal",
        color: "#4a044e",
        textAlign: "left",
      },
      {
        id: "sticker_heart",
        type: "sticker",
        x: 680,
        y: 110,
        width: 50,
        height: 50,
        rotation: -10,
        zIndex: 15,
        content: "💖",
        fontSize: 36,
      },
      {
        id: "sticker_sparkles",
        type: "sticker",
        x: 80,
        y: 540,
        width: 45,
        height: 45,
        rotation: 15,
        zIndex: 15,
        content: "✨",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 600,
              width: 660,
              height: 130,
              rotation: 1,
              zIndex: 12,
              content: aiSummary,
              caption: "🌸 Heartfelt Insight",
              backgroundColor: "#fce7f3",
              borderColor: "#fbcfe8",
              color: "#831843",
            },
          ]
        : []),
    ],
  },
  {
    id: "photo_scrapbook",
    name: "Photo Scrapbook",
    badge: "📸",
    description: "Rustic kraft paper with tilted polaroids, washi tape, and pin stamps.",
    paperStyle: "kraft_paper",
    paperColor: "#EADBCA",
    fontFamily: "Kalam",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_top_kraft",
        type: "tape",
        x: 300,
        y: 15,
        width: 160,
        height: 30,
        rotation: 2,
        zIndex: 5,
        tapeColor: "bg-[#c8ad8d]/85 border-[#b69976]",
      },
      {
        id: "entry_title",
        type: "text",
        x: 50,
        y: 60,
        width: 680,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Scrapbook Memories",
        fontFamily: "Kalam",
        fontSize: 32,
        fontWeight: "bold",
        color: "#292524",
      },
      {
        id: "date_badge",
        type: "text",
        x: 50,
        y: 120,
        width: 300,
        height: 30,
        rotation: -1,
        zIndex: 10,
        content: `🏷️ Captured: ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 14,
        color: "#57534e",
      },
      {
        id: "demo_polaroid",
        type: "image",
        x: 480,
        y: 170,
        width: 250,
        height: 290,
        rotation: 4,
        zIndex: 12,
        imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
        caption: "A quiet moment of serenity 🍃",
        photoStyle: "polaroid",
      },
      {
        id: "main_body",
        type: "text",
        x: 50,
        y: 170,
        width: 400,
        height: 360,
        rotation: 0,
        zIndex: 10,
        content: text || "Paste your favorite photos and candid moments here! Drag images directly onto this paper page, resize the corners, and rotate them just like physical scrapbook prints.",
        fontFamily: "Kalam",
        fontSize: 18,
        color: "#1c1917",
      },
      {
        id: "sticker_pin",
        type: "sticker",
        x: 590,
        y: 145,
        width: 40,
        height: 40,
        rotation: 0,
        zIndex: 20,
        content: "📌",
        fontSize: 28,
      },
      {
        id: "sticker_camera",
        type: "sticker",
        x: 60,
        y: 540,
        width: 45,
        height: 45,
        rotation: -8,
        zIndex: 15,
        content: "📸",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 50,
              y: 590,
              width: 680,
              height: 130,
              rotation: -1,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Reflection",
              backgroundColor: "#f5f5f4",
              borderColor: "#e7e5e4",
              color: "#292524",
            },
          ]
        : []),
    ],
  },
  {
    id: "classic_diary",
    name: "Classic Diary",
    badge: "📓",
    description: "Ruled blue notebook lines with red margin and typewriter font.",
    paperStyle: "ruled_notebook",
    paperColor: "#FDFCF7",
    fontFamily: "Courier Prime",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "entry_title",
        type: "text",
        x: 90,
        y: 60,
        width: 640,
        height: 55,
        rotation: 0,
        zIndex: 10,
        content: title || "Dear Diary,",
        fontFamily: "Newsreader",
        fontSize: 28,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#1e293b",
      },
      {
        id: "date_badge",
        type: "text",
        x: 540,
        y: 35,
        width: 190,
        height: 30,
        rotation: 0,
        zIndex: 10,
        content: date,
        fontFamily: "Courier Prime",
        fontSize: 14,
        fontWeight: "bold",
        color: "#b91c1c",
        textAlign: "right",
      },
      {
        id: "main_body",
        type: "text",
        x: 90,
        y: 130,
        width: 640,
        height: 440,
        rotation: 0,
        zIndex: 10,
        content: text || "Today felt different in a meaningful way. As the morning began, I noticed...",
        fontFamily: "Courier Prime",
        fontSize: 16,
        fontWeight: "normal",
        color: "#0f172a",
        textAlign: "left",
      },
      {
        id: "sticker_coffee",
        type: "sticker",
        x: 670,
        y: 80,
        width: 45,
        height: 45,
        rotation: 5,
        zIndex: 15,
        content: "☕",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 90,
              y: 590,
              width: 640,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Summary Reflection",
              backgroundColor: "#f1f5f9",
              borderColor: "#e2e8f0",
              color: "#334155",
            },
          ]
        : []),
    ],
  },
  {
    id: "memory_board",
    name: "Memory Board",
    badge: "✨",
    description: "Architectural dot grid with sticky notes, colorful badges, and pins.",
    paperStyle: "dot_grid",
    paperColor: "#F8F7F4",
    fontFamily: "Plus Jakarta Sans",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "entry_title",
        type: "text",
        x: 50,
        y: 50,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Ideas & Moments Board",
        fontFamily: "Plus Jakarta Sans",
        fontSize: 28,
        fontWeight: "bold",
        color: "#0f172a",
      },
      {
        id: "date_badge",
        type: "text",
        x: 560,
        y: 60,
        width: 170,
        height: 35,
        rotation: -2,
        zIndex: 10,
        content: `📍 ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 13,
        color: "#475569",
        backgroundColor: "#fef08a",
        borderRadius: 8,
        textAlign: "center",
      },
      {
        id: "sticky_note_1",
        type: "text",
        x: 50,
        y: 130,
        width: 320,
        height: 280,
        rotation: -2,
        zIndex: 11,
        content: text || "Capture raw observations, eureka thoughts, or memorable quotes from today!",
        fontFamily: "Kalam",
        fontSize: 17,
        color: "#713f12",
        backgroundColor: "#fef9c3",
        borderRadius: 12,
        borderColor: "#fef08a",
        borderWidth: 1,
      },
      {
        id: "pin_sticky",
        type: "sticker",
        x: 190,
        y: 115,
        width: 35,
        height: 35,
        rotation: 0,
        zIndex: 20,
        content: "📌",
        fontSize: 26,
      },
      {
        id: "demo_photo_board",
        type: "image",
        x: 410,
        y: 130,
        width: 320,
        height: 280,
        rotation: 3,
        zIndex: 11,
        imageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600&auto=format&fit=crop&q=80",
        caption: "Golden sunlight filtering through 🌿",
        photoStyle: "tape",
      },
      {
        id: "sticker_star",
        type: "sticker",
        x: 680,
        y: 430,
        width: 40,
        height: 40,
        rotation: 12,
        zIndex: 15,
        content: "⭐",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 50,
              y: 450,
              width: 680,
              height: 150,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Synthesis & Key Themes",
              backgroundColor: "#e0f2fe",
              borderColor: "#bae6fd",
              color: "#0369a1",
            },
          ]
        : []),
    ],
  },
  {
    id: "nature_journal",
    name: "Nature Journal",
    badge: "🌿",
    description: "Botanical sage paper with leaf stamps, grounding tones, and harmony.",
    paperStyle: "sage_meadow",
    paperColor: "#F0F5F1",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_nature",
        type: "tape",
        x: 320,
        y: 15,
        width: 140,
        height: 28,
        rotation: -2,
        zIndex: 5,
        tapeColor: "bg-emerald-300/80 border-emerald-400",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 240,
        height: 30,
        rotation: 0,
        zIndex: 10,
        content: `🌿 Field Note: ${date}`,
        fontFamily: "Newsreader",
        fontSize: 15,
        fontStyle: "italic",
        color: "#065f46",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 85,
        width: 660,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Reflections in Nature",
        fontFamily: "Playfair Display",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#064e3b",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 160,
        width: 660,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Observing the natural world: sounds of the wind, texture of the earth, and the stillness within.",
        fontFamily: "Newsreader",
        fontSize: 18,
        color: "#134e4a",
        textAlign: "left",
      },
      {
        id: "sticker_leaf_1",
        type: "sticker",
        x: 690,
        y: 50,
        width: 45,
        height: 45,
        rotation: 15,
        zIndex: 15,
        content: "🍃",
        fontSize: 34,
      },
      {
        id: "sticker_butterfly",
        type: "sticker",
        x: 80,
        y: 560,
        width: 45,
        height: 45,
        rotation: -10,
        zIndex: 15,
        content: "🦋",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 610,
              width: 660,
              height: 130,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Grounding Reflection",
              backgroundColor: "#d1fae5",
              borderColor: "#a7f3d0",
              color: "#065f46",
            },
          ]
        : []),
    ],
  },
];
