import { PaperStyle, JournalFontFamily, ScrapbookElement, ScrapbookLayout } from "../types";

export interface PaperStyleMeta {
  id: PaperStyle;
  label: string;
  icon: string;
  bgClass: string;
  defaultBgColor: string;
  description: string;
  cssStyle?: React.CSSProperties;
}

export const PAPER_STYLES: PaperStyleMeta[] = [
  {
    id: "cream_linen",
    label: "Cream Linen",
    icon: "📜",
    bgClass: "bg-[#FAF7F2] text-stone-900",
    defaultBgColor: "#FAF7F2",
    description: "Warm, timeless artisan stationery with a soft natural texture.",
  },
  {
    id: "ruled_notebook",
    label: "Ruled Notebook",
    icon: "📓",
    bgClass: "bg-[#FDFCF7] text-stone-900",
    defaultBgColor: "#FDFCF7",
    description: "Classic college-ruled journal with subtle blue guidelines & red margin.",
  },
  {
    id: "dot_grid",
    label: "Dot Grid",
    icon: "📐",
    bgClass: "bg-[#F8F7F4] text-stone-900",
    defaultBgColor: "#F8F7F4",
    description: "Architectural bullet journal dot-matrix for structured scrapbooking.",
  },
  {
    id: "grid_graph",
    label: "Graph Paper",
    icon: "▦",
    bgClass: "bg-[#F9FAF8] text-stone-900",
    defaultBgColor: "#F9FAF8",
    description: "Clean quad-ruled engineering graph grid for structured journaling.",
  },
  {
    id: "kraft_paper",
    label: "Kraft Paper",
    icon: "📦",
    bgClass: "bg-[#EADBCA] text-stone-950",
    defaultBgColor: "#EADBCA",
    description: "Warm vintage recycled parcel craft paper with organic charm.",
  },
  {
    id: "soft_rose",
    label: "Soft Pastel",
    icon: "🌸",
    bgClass: "bg-[#FFF4F6] text-stone-900",
    defaultBgColor: "#FFF4F6",
    description: "Delicate blush tinted paper for heartfelt, intimate reflections.",
  },
  {
    id: "watercolor_blush",
    label: "Watercolor Wash",
    icon: "🎨",
    bgClass: "bg-[#FFF8F5] text-stone-900",
    defaultBgColor: "#FFF8F5",
    description: "Soft painted watercolor blooms and artisan paper edges.",
  },
  {
    id: "vintage_parchment",
    label: "Vintage Parchment",
    icon: "📜",
    bgClass: "bg-[#F5EFE0] text-amber-950",
    defaultBgColor: "#F5EFE0",
    description: "Aged antiquarian manuscript paper with warm sepia undertones.",
  },
  {
    id: "stained_aged",
    label: "Aged Tea Stain",
    icon: "☕",
    bgClass: "bg-[#F2E8D5] text-stone-900",
    defaultBgColor: "#F2E8D5",
    description: "Antiqued deckle-edge paper with subtle coffee stains and warm patina.",
  },
  {
    id: "sage_meadow",
    label: "Sage Meadow",
    icon: "🌿",
    bgClass: "bg-[#F0F5F1] text-emerald-950",
    defaultBgColor: "#F0F5F1",
    description: "Calm botanical soft green paper evocative of spring leaves.",
  },
  {
    id: "retro_film",
    label: "Retro Kodachrome",
    icon: "🎞️",
    bgClass: "bg-[#F7F4EB] text-stone-900",
    defaultBgColor: "#F7F4EB",
    description: "Nostalgic golden-hour film tone with warm grain and analog feel.",
  },
  {
    id: "midnight_journal",
    label: "Midnight Ink",
    icon: "🌑",
    bgClass: "bg-[#1E1F24] text-stone-100",
    defaultBgColor: "#1E1F24",
    description: "Deep nocturnal dark paper with starry gold & chalk accents.",
  },
];

export interface ColorPaletteTheme {
  id: string;
  name: string;
  badge: string;
  paperStyle: PaperStyle;
  primaryColor: string;
  accentColor: string;
  description: string;
}

export const COLOR_PALETTES: ColorPaletteTheme[] = [
  {
    id: "parchment_warmth",
    name: "Parchment Warmth",
    badge: "📜",
    paperStyle: "vintage_parchment",
    primaryColor: "#78350f",
    accentColor: "#d97706",
    description: "Warm sepia tones, aged ink, and timeless literary comfort.",
  },
  {
    id: "botanical_garden",
    name: "Botanical Garden",
    badge: "🌿",
    paperStyle: "sage_meadow",
    primaryColor: "#065f46",
    accentColor: "#10b981",
    description: "Earthy greens, herbal illustrations, and gentle grounding calm.",
  },
  {
    id: "sunset_memories",
    name: "Sunset Memories",
    badge: "🌅",
    paperStyle: "retro_film",
    primaryColor: "#9a3412",
    accentColor: "#f97316",
    description: "Golden hour glow, amber washi tape, and nostalgic warmth.",
  },
  {
    id: "lavender_dreams",
    name: "Lavender Dreams",
    badge: "💜",
    paperStyle: "soft_rose",
    primaryColor: "#6b21a8",
    accentColor: "#a855f7",
    description: "Lilac washes, peaceful tranquility, and dreamy mindfulness.",
  },
  {
    id: "monochrome_minimalist",
    name: "Monochrome Minimalist",
    badge: "✒️",
    paperStyle: "cream_linen",
    primaryColor: "#18181b",
    accentColor: "#71717a",
    description: "Crisp black ink, generous whitespace, and pure editorial clarity.",
  },
  {
    id: "retro_film",
    name: "Retro Kodachrome",
    badge: "🎞️",
    paperStyle: "retro_film",
    primaryColor: "#7c2d12",
    accentColor: "#ea580c",
    description: "Analog camera aesthetic, polaroid snapshots, and vintage vibes.",
  },
  {
    id: "dark_starry_night",
    name: "Dark Starry Night",
    badge: "✨",
    paperStyle: "midnight_journal",
    primaryColor: "#fef08a",
    accentColor: "#60a5fa",
    description: "Deep indigo darkness, golden constellations, and nocturnal reflections.",
  },
  {
    id: "coffee_kraft",
    name: "Coffee & Kraft",
    badge: "☕",
    paperStyle: "kraft_paper",
    primaryColor: "#451a03",
    accentColor: "#92400e",
    description: "Warm espresso stains, recycled organic paper, and rustic diary notes.",
  },
];

export const JOURNAL_FONTS: { id: JournalFontFamily; label: string; preview: string; cssFamily: string }[] = [
  {
    id: "Newsreader",
    label: "Newsreader (Editorial Serif)",
    preview: "Reflective and timeless",
    cssFamily: "'Newsreader', Georgia, serif",
  },
  {
    id: "Kalam",
    label: "Kalam (Casual Handwriting)",
    preview: "Personal handwritten thoughts",
    cssFamily: "'Kalam', cursive",
  },
  {
    id: "Caveat",
    label: "Caveat (Expressive Script)",
    preview: "Fluid handwritten diary entry",
    cssFamily: "'Caveat', cursive",
  },
  {
    id: "Courier Prime",
    label: "Courier Prime (Vintage Typewriter)",
    preview: "Mechanical typewriter aesthetic",
    cssFamily: "'Courier Prime', monospace",
  },
  {
    id: "Playfair Display",
    label: "Playfair Display (Literary Classic)",
    preview: "Elegant bookcraft titles",
    cssFamily: "'Playfair Display', serif",
  },
  {
    id: "Plus Jakarta Sans",
    label: "Plus Jakarta (Clean Modern)",
    preview: "Minimal modern clarity",
    cssFamily: "'Plus Jakarta Sans', sans-serif",
  },
];

export const WASHI_TAPE_COLORS = [
  { id: "amber", name: "Amber Ochre", bg: "bg-amber-300/80 border-amber-400" },
  { id: "rose", name: "Blush Rose", bg: "bg-rose-300/80 border-rose-400" },
  { id: "sage", name: "Sage Mint", bg: "bg-emerald-300/80 border-emerald-400" },
  { id: "cyan", name: "Sky Cyan", bg: "bg-cyan-300/80 border-cyan-400" },
  { id: "lavender", name: "Soft Lavender", bg: "bg-purple-300/80 border-purple-400" },
  { id: "kraft", name: "Kraft Brown", bg: "bg-[#c8ad8d]/85 border-[#b69976]" },
  { id: "striped_gold", name: "Gold Stripes", bg: "bg-gradient-to-r from-amber-200 via-yellow-300 to-amber-200 border-amber-400" },
  { id: "glitter_gold", name: "Glitter Metallic", bg: "bg-amber-200/90 border-dashed border-amber-500" },
  { id: "gingham_blue", name: "Gingham Grid", bg: "bg-sky-200/85 border-sky-300" },
  { id: "cherry_blossom", name: "Cherry Floral", bg: "bg-pink-300/85 border-pink-400" },
];

export const STAMP_OPTIONS = [
  { text: "RECORDED", color: "#b91c1c", label: "Vintage Red Recorded" },
  { text: "GRATEFUL", color: "#047857", label: "Emerald Grateful" },
  { text: "MINDFUL", color: "#6d28d9", label: "Purple Mindful" },
  { text: "CHERISHED", color: "#be185d", label: "Rose Cherished" },
  { text: "DEAR DIARY", color: "#451a03", label: "Sepia Dear Diary" },
  { text: "CONFIDENTIAL 🔒", color: "#1e3a8a", label: "Navy Confidential" },
  { text: "VERIFIED", color: "#0369a1", label: "Sky Verified" },
  { text: "BIG WIN ⭐", color: "#b45309", label: "Amber Big Win" },
];

export const STICKER_PACKS = [
  {
    category: "Mindful & Nature",
    stickers: ["🌿", "🌸", "🌱", "🍃", "☕", "🕯️", "🌞", "🌙", "✨", "🦋", "🌻", "🍂", "🍄", "🌊"],
  },
  {
    category: "Scrapbook & Stationery",
    stickers: ["📌", "📎", "🏷️", "💌", "📖", "🎨", "🎀", "📜", "🔖", "🔑", "✂️", "✏️", "🧶", "🧵"],
  },
  {
    category: "Emotions & Memory",
    stickers: ["😊", "💭", "🔥", "🌈", "💎", "🎯", "📸", "🎈", "🧸", "🕊️", "💖", "⭐", "💫", "🕊️"],
  },
  {
    category: "Doodles & Flourishes",
    stickers: ["✦", "➔", "〰️", "❧", "❋", "✣", "🪶", "🪞", "🗝️", "🪄", "💡", "🎶", "⏳", "🧭"],
  },
];

export interface JournalTemplate {
  id: string;
  name: string;
  badge: string;
  description: string;
  paperStyle: PaperStyle;
  paperColor: string;
  fontFamily: JournalFontFamily;
  generateElements: (title: string, date: string, text: string, aiSummary?: string) => ScrapbookElement[];
}

export const JOURNAL_TEMPLATES: JournalTemplate[] = [
  {
    id: "minimal_paper",
    name: "Minimal Paper",
    badge: "📄",
    description: "Clean cream stationery with refined typography and pencil rules.",
    paperStyle: "cream_linen",
    paperColor: "#FAF7F2",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_top",
        type: "tape",
        x: 320,
        y: 12,
        width: 140,
        height: 28,
        rotation: -1,
        zIndex: 5,
        tapeColor: "bg-amber-200/80 border-amber-300",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 260,
        height: 35,
        rotation: 0,
        zIndex: 10,
        content: `🗓️ ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#78716c",
        textAlign: "left",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 90,
        width: 660,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Reflective Journal",
        fontFamily: "Playfair Display",
        fontSize: 30,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#1c1917",
        textAlign: "left",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 165,
        width: 660,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Write your authentic reflections here... Notice the sensations, emotions, and thoughts moving through your day.",
        fontFamily: "Newsreader",
        fontSize: 17,
        fontWeight: "normal",
        fontStyle: "normal",
        color: "#292524",
        textAlign: "left",
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 580,
              width: 660,
              height: 140,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Reflection Insight",
              backgroundColor: "#fef3c7",
              borderColor: "#fde68a",
              color: "#78350f",
            },
          ]
        : []),
      {
        id: "decor_leaf",
        type: "sticker",
        x: 690,
        y: 45,
        width: 50,
        height: 50,
        rotation: 12,
        zIndex: 15,
        content: "🌿",
        fontSize: 32,
      },
    ],
  },
  {
    id: "soft_pastel",
    name: "Soft Pastel",
    badge: "🌸",
    description: "Dreamy blush pink with expressive handwriting and sweet stickers.",
    paperStyle: "soft_rose",
    paperColor: "#FFF4F6",
    fontFamily: "Caveat",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_corner_1",
        type: "tape",
        x: 40,
        y: 20,
        width: 120,
        height: 26,
        rotation: -8,
        zIndex: 5,
        tapeColor: "bg-rose-300/80 border-rose-400",
      },
      {
        id: "tape_corner_2",
        type: "tape",
        x: 620,
        y: 25,
        width: 110,
        height: 26,
        rotation: 10,
        zIndex: 5,
        tapeColor: "bg-purple-300/80 border-purple-400",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 80,
        width: 660,
        height: 65,
        rotation: -1,
        zIndex: 10,
        content: title || "A gentle check-in with my heart",
        fontFamily: "Kalam",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "normal",
        color: "#831843",
        textAlign: "left",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 220,
        height: 30,
        rotation: 2,
        zIndex: 10,
        content: `🌸 ${date}`,
        fontFamily: "Caveat",
        fontSize: 18,
        color: "#9d174d",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 160,
        width: 660,
        height: 360,
        rotation: 0,
        zIndex: 10,
        content: text || "Pour your heart out gently onto the page. There are no right or wrong words here, just honest feelings.",
        fontFamily: "Caveat",
        fontSize: 22,
        fontWeight: "normal",
        color: "#4a044e",
        textAlign: "left",
      },
      {
        id: "sticker_heart",
        type: "sticker",
        x: 680,
        y: 110,
        width: 50,
        height: 50,
        rotation: -10,
        zIndex: 15,
        content: "💖",
        fontSize: 36,
      },
      {
        id: "sticker_sparkles",
        type: "sticker",
        x: 80,
        y: 540,
        width: 45,
        height: 45,
        rotation: 15,
        zIndex: 15,
        content: "✨",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 600,
              width: 660,
              height: 130,
              rotation: 1,
              zIndex: 12,
              content: aiSummary,
              caption: "🌸 Heartfelt Insight",
              backgroundColor: "#fce7f3",
              borderColor: "#fbcfe8",
              color: "#831843",
            },
          ]
        : []),
    ],
  },
  {
    id: "photo_scrapbook",
    name: "Photo Scrapbook",
    badge: "📸",
    description: "Rustic kraft paper with tilted polaroids, washi tape, and pin stamps.",
    paperStyle: "kraft_paper",
    paperColor: "#EADBCA",
    fontFamily: "Kalam",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_top_kraft",
        type: "tape",
        x: 300,
        y: 15,
        width: 160,
        height: 30,
        rotation: 2,
        zIndex: 5,
        tapeColor: "bg-[#c8ad8d]/85 border-[#b69976]",
      },
      {
        id: "entry_title",
        type: "text",
        x: 50,
        y: 60,
        width: 680,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Scrapbook Memories",
        fontFamily: "Kalam",
        fontSize: 32,
        fontWeight: "bold",
        color: "#292524",
      },
      {
        id: "date_badge",
        type: "text",
        x: 50,
        y: 120,
        width: 300,
        height: 30,
        rotation: -1,
        zIndex: 10,
        content: `🏷️ Captured: ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 14,
        color: "#57534e",
      },
      {
        id: "demo_polaroid",
        type: "image",
        x: 480,
        y: 170,
        width: 250,
        height: 290,
        rotation: 4,
        zIndex: 12,
        imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
        caption: "A quiet moment of serenity 🍃",
        photoStyle: "polaroid",
      },
      {
        id: "main_body",
        type: "text",
        x: 50,
        y: 170,
        width: 400,
        height: 360,
        rotation: 0,
        zIndex: 10,
        content: text || "Paste your favorite photos and candid moments here! Drag images directly onto this paper page, resize the corners, and rotate them just like physical scrapbook prints.",
        fontFamily: "Kalam",
        fontSize: 18,
        color: "#1c1917",
      },
      {
        id: "sticker_pin",
        type: "sticker",
        x: 590,
        y: 145,
        width: 40,
        height: 40,
        rotation: 0,
        zIndex: 20,
        content: "📌",
        fontSize: 28,
      },
      {
        id: "sticker_camera",
        type: "sticker",
        x: 60,
        y: 540,
        width: 45,
        height: 45,
        rotation: -8,
        zIndex: 15,
        content: "📸",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 50,
              y: 590,
              width: 680,
              height: 130,
              rotation: -1,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Reflection",
              backgroundColor: "#f5f5f4",
              borderColor: "#e7e5e4",
              color: "#292524",
            },
          ]
        : []),
    ],
  },
  {
    id: "classic_diary",
    name: "Classic Diary",
    badge: "📓",
    description: "Ruled blue notebook lines with red margin and typewriter font.",
    paperStyle: "ruled_notebook",
    paperColor: "#FDFCF7",
    fontFamily: "Courier Prime",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "entry_title",
        type: "text",
        x: 90,
        y: 60,
        width: 640,
        height: 55,
        rotation: 0,
        zIndex: 10,
        content: title || "Dear Diary,",
        fontFamily: "Newsreader",
        fontSize: 28,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#1e293b",
      },
      {
        id: "date_badge",
        type: "text",
        x: 540,
        y: 35,
        width: 190,
        height: 30,
        rotation: 0,
        zIndex: 10,
        content: date,
        fontFamily: "Courier Prime",
        fontSize: 14,
        fontWeight: "bold",
        color: "#b91c1c",
        textAlign: "right",
      },
      {
        id: "main_body",
        type: "text",
        x: 90,
        y: 130,
        width: 640,
        height: 440,
        rotation: 0,
        zIndex: 10,
        content: text || "Today felt different in a meaningful way. As the morning began, I noticed...",
        fontFamily: "Courier Prime",
        fontSize: 16,
        fontWeight: "normal",
        color: "#0f172a",
        textAlign: "left",
      },
      {
        id: "sticker_coffee",
        type: "sticker",
        x: 670,
        y: 80,
        width: 45,
        height: 45,
        rotation: 5,
        zIndex: 15,
        content: "☕",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 90,
              y: 590,
              width: 640,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Summary Reflection",
              backgroundColor: "#f1f5f9",
              borderColor: "#e2e8f0",
              color: "#334155",
            },
          ]
        : []),
    ],
  },
  {
    id: "memory_board",
    name: "Memory Board",
    badge: "✨",
    description: "Architectural dot grid with sticky notes, colorful badges, and pins.",
    paperStyle: "dot_grid",
    paperColor: "#F8F7F4",
    fontFamily: "Plus Jakarta Sans",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "entry_title",
        type: "text",
        x: 50,
        y: 50,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Ideas & Moments Board",
        fontFamily: "Plus Jakarta Sans",
        fontSize: 28,
        fontWeight: "bold",
        color: "#0f172a",
      },
      {
        id: "date_badge",
        type: "text",
        x: 560,
        y: 60,
        width: 170,
        height: 35,
        rotation: -2,
        zIndex: 10,
        content: `📍 ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 13,
        color: "#475569",
        backgroundColor: "#fef08a",
        borderRadius: 8,
        textAlign: "center",
      },
      {
        id: "sticky_note_1",
        type: "text",
        x: 50,
        y: 130,
        width: 320,
        height: 280,
        rotation: -2,
        zIndex: 11,
        content: text || "Capture raw observations, eureka thoughts, or memorable quotes from today!",
        fontFamily: "Kalam",
        fontSize: 17,
        color: "#713f12",
        backgroundColor: "#fef9c3",
        borderRadius: 12,
        borderColor: "#fef08a",
        borderWidth: 1,
      },
      {
        id: "pin_sticky",
        type: "sticker",
        x: 190,
        y: 115,
        width: 35,
        height: 35,
        rotation: 0,
        zIndex: 20,
        content: "📌",
        fontSize: 26,
      },
      {
        id: "demo_photo_board",
        type: "image",
        x: 410,
        y: 130,
        width: 320,
        height: 280,
        rotation: 3,
        zIndex: 11,
        imageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600&auto=format&fit=crop&q=80",
        caption: "Golden sunlight filtering through 🌿",
        photoStyle: "tape",
      },
      {
        id: "sticker_star",
        type: "sticker",
        x: 680,
        y: 430,
        width: 40,
        height: 40,
        rotation: 12,
        zIndex: 15,
        content: "⭐",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 50,
              y: 450,
              width: 680,
              height: 150,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Gemini Synthesis & Key Themes",
              backgroundColor: "#e0f2fe",
              borderColor: "#bae6fd",
              color: "#0369a1",
            },
          ]
        : []),
    ],
  },
  {
    id: "nature_journal",
    name: "Nature Journal",
    badge: "🌿",
    description: "Botanical sage paper with leaf stamps, grounding tones, and harmony.",
    paperStyle: "sage_meadow",
    paperColor: "#F0F5F1",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_nature",
        type: "tape",
        x: 320,
        y: 15,
        width: 140,
        height: 28,
        rotation: -2,
        zIndex: 5,
        tapeColor: "bg-emerald-300/80 border-emerald-400",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 50,
        width: 240,
        height: 30,
        rotation: 0,
        zIndex: 10,
        content: `🌿 Field Note: ${date}`,
        fontFamily: "Newsreader",
        fontSize: 15,
        fontStyle: "italic",
        color: "#065f46",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 85,
        width: 660,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Reflections in Nature",
        fontFamily: "Playfair Display",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#064e3b",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 160,
        width: 660,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Observing the natural world: sounds of the wind, texture of the earth, and the stillness within.",
        fontFamily: "Newsreader",
        fontSize: 18,
        color: "#134e4a",
        textAlign: "left",
      },
      {
        id: "sticker_leaf_1",
        type: "sticker",
        x: 690,
        y: 50,
        width: 45,
        height: 45,
        rotation: 15,
        zIndex: 15,
        content: "🍃",
        fontSize: 34,
      },
      {
        id: "sticker_butterfly",
        type: "sticker",
        x: 80,
        y: 560,
        width: 45,
        height: 45,
        rotation: -10,
        zIndex: 15,
        content: "🦋",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 610,
              width: 660,
              height: 130,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Grounding Reflection",
              backgroundColor: "#d1fae5",
              borderColor: "#a7f3d0",
              color: "#065f46",
            },
          ]
        : []),
    ],
  },
  {
    id: "travel_diary",
    name: "Travel & Adventure",
    badge: "✈️",
    description: "Passport stamp style, polaroid snapshot, washi tape, and wanderlust notes.",
    paperStyle: "retro_film",
    paperColor: "#F7F4EB",
    fontFamily: "Courier Prime",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_travel",
        type: "tape",
        x: 310,
        y: 12,
        width: 160,
        height: 30,
        rotation: 1,
        zIndex: 5,
        tapeColor: "bg-[#c8ad8d]/85 border-[#b69976]",
      },
      {
        id: "stamp_recorded",
        type: "stamp",
        x: 570,
        y: 40,
        width: 150,
        height: 50,
        rotation: -7,
        zIndex: 12,
        stampText: "RECORDED",
        stampColor: "#b91c1c",
        stampVariant: "rect",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 60,
        width: 480,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Wanderlust Dispatch",
        fontFamily: "Playfair Display",
        fontSize: 30,
        fontWeight: "bold",
        color: "#7c2d12",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 120,
        width: 250,
        height: 30,
        rotation: 0,
        zIndex: 10,
        content: `📍 Expedition Date: ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 13,
        color: "#9a3412",
      },
      {
        id: "travel_photo",
        type: "image",
        x: 430,
        y: 160,
        width: 300,
        height: 320,
        rotation: 3,
        zIndex: 11,
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
        caption: "Coastal horizon & golden breeze ✨",
        photoStyle: "polaroid",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 160,
        width: 340,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Exploring unfamiliar streets, tasting authentic flavors, and recording moments that will stay forever in memory...",
        fontFamily: "Courier Prime",
        fontSize: 15,
        color: "#431407",
        textAlign: "left",
      },
      {
        id: "sticker_compass",
        type: "sticker",
        x: 680,
        y: 500,
        width: 45,
        height: 45,
        rotation: -8,
        zIndex: 15,
        content: "🧭",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 570,
              width: 670,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Travel Memory Synthesis",
              backgroundColor: "#ffedd5",
              borderColor: "#fed7aa",
              color: "#9a3412",
            },
          ]
        : []),
    ],
  },
  {
    id: "gratitude_affirmation",
    name: "Gratitude & Affirmation",
    badge: "💖",
    description: "Soft pastel blush paper with gratitude stamps, heart stickers, and sticky notes.",
    paperStyle: "soft_rose",
    paperColor: "#FFF4F6",
    fontFamily: "Caveat",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "stamp_grateful",
        type: "stamp",
        x: 580,
        y: 35,
        width: 140,
        height: 48,
        rotation: 4,
        zIndex: 12,
        stampText: "GRATEFUL",
        stampColor: "#047857",
        stampVariant: "rect",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 50,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Daily Gratitudes & Joys",
        fontFamily: "Caveat",
        fontSize: 36,
        fontWeight: "bold",
        color: "#831843",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 110,
        width: 200,
        height: 28,
        rotation: 0,
        zIndex: 10,
        content: `💖 Moment: ${date}`,
        fontFamily: "Newsreader",
        fontSize: 14,
        fontStyle: "italic",
        color: "#be185d",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 150,
        width: 400,
        height: 380,
        rotation: -1,
        zIndex: 10,
        content: text || "Three things I deeply appreciate today:\n1. The quiet morning silence before dawn.\n2. A kind text from an old friend.\n3. The courage to keep growing.",
        fontFamily: "Caveat",
        fontSize: 22,
        color: "#500724",
        textAlign: "left",
      },
      {
        id: "sticky_affirmation",
        type: "text",
        x: 490,
        y: 160,
        width: 240,
        height: 220,
        rotation: 3,
        zIndex: 11,
        content: "✨ Daily Affirmation:\nI am patient with my path. Every step forward counts.",
        fontFamily: "Kalam",
        fontSize: 17,
        color: "#831843",
        backgroundColor: "#fce7f3",
        borderColor: "#fbcfe8",
        borderWidth: 1,
        borderRadius: 12,
      },
      {
        id: "sticker_heart",
        type: "sticker",
        x: 670,
        y: 400,
        width: 45,
        height: 45,
        rotation: 10,
        zIndex: 15,
        content: "💖",
        fontSize: 32,
      },
      {
        id: "sticker_flower",
        type: "sticker",
        x: 480,
        y: 420,
        width: 45,
        height: 45,
        rotation: -5,
        zIndex: 15,
        content: "🌸",
        fontSize: 32,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 560,
              width: 670,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Emotional Harmony Reflection",
              backgroundColor: "#fdf2f8",
              borderColor: "#fce7f3",
              color: "#9d174d",
            },
          ]
        : []),
    ],
  },
  {
    id: "deep_essay",
    name: "Deep Thought & Essay",
    badge: "📜",
    description: "Antiquarian parchment, drop quotes, editorial serif, and contemplative space.",
    paperStyle: "vintage_parchment",
    paperColor: "#F5EFE0",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "entry_title",
        type: "text",
        x: 70,
        y: 60,
        width: 650,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Essays on Becoming",
        fontFamily: "Playfair Display",
        fontSize: 34,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#451a03",
      },
      {
        id: "date_badge",
        type: "text",
        x: 70,
        y: 120,
        width: 250,
        height: 25,
        rotation: 0,
        zIndex: 10,
        content: `Folio entry — ${date}`,
        fontFamily: "Newsreader",
        fontSize: 14,
        fontStyle: "italic",
        color: "#92400e",
      },
      {
        id: "quote_callout",
        type: "quote_card",
        x: 70,
        y: 160,
        width: 650,
        height: 90,
        rotation: 0,
        zIndex: 11,
        content: "“In the depth of winter, I finally learned that within me there lay an invincible summer.”",
        caption: "Albert Camus",
        fontFamily: "Newsreader",
        fontSize: 17,
        fontStyle: "italic",
        color: "#78350f",
        backgroundColor: "#fef3c7",
        borderColor: "#fde68a",
        borderWidth: 1,
        borderRadius: 8,
      },
      {
        id: "main_body",
        type: "text",
        x: 70,
        y: 270,
        width: 650,
        height: 380,
        rotation: 0,
        zIndex: 10,
        content: text || "Reflecting deeply on what anchors us during times of transformation...",
        fontFamily: "Newsreader",
        fontSize: 18,
        color: "#292524",
        textAlign: "left",
      },
      {
        id: "sticker_quill",
        type: "sticker",
        x: 680,
        y: 115,
        width: 40,
        height: 40,
        rotation: 15,
        zIndex: 15,
        content: "🪶",
        fontSize: 28,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 70,
              y: 660,
              width: 650,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Philosophical Synthesis",
              backgroundColor: "#fae8b6",
              borderColor: "#e5d59e",
              color: "#78350f",
            },
          ]
        : []),
    ],
  },
  {
    id: "bullet_journal",
    name: "Bullet Journal & Productivity",
    badge: "▦",
    description: "Grid graph paper, structure checklists, verified stamps, and goal tracking.",
    paperStyle: "grid_graph",
    paperColor: "#F9FAF8",
    fontFamily: "Plus Jakarta Sans",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "stamp_verified",
        type: "stamp",
        x: 580,
        y: 40,
        width: 140,
        height: 45,
        rotation: -4,
        zIndex: 12,
        stampText: "VERIFIED",
        stampColor: "#0369a1",
        stampVariant: "rect",
      },
      {
        id: "entry_title",
        type: "text",
        x: 60,
        y: 50,
        width: 500,
        height: 50,
        rotation: 0,
        zIndex: 10,
        content: title || "Sprint Log & Focus Points",
        fontFamily: "Plus Jakarta Sans",
        fontSize: 28,
        fontWeight: "bold",
        color: "#0f172a",
      },
      {
        id: "date_badge",
        type: "text",
        x: 60,
        y: 105,
        width: 250,
        height: 25,
        rotation: 0,
        zIndex: 10,
        content: `TRACK LOG: ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 13,
        fontWeight: "bold",
        color: "#0284c7",
      },
      {
        id: "main_body",
        type: "text",
        x: 60,
        y: 145,
        width: 440,
        height: 420,
        rotation: 0,
        zIndex: 10,
        content: text || "• [x] Morning mindfulness meditation (15 min)\n• [x] Deep focus writing block completed\n• [ ] Review creative reflections\n• [ ] Evening wind-down walk",
        fontFamily: "Plus Jakarta Sans",
        fontSize: 16,
        color: "#1e293b",
        textAlign: "left",
      },
      {
        id: "sticky_goals",
        type: "text",
        x: 520,
        y: 145,
        width: 210,
        height: 240,
        rotation: 2,
        zIndex: 11,
        content: "⭐ KEY WINS:\n- Focused flow\n- Zero interruptions\n- Deep calm maintained",
        fontFamily: "Kalam",
        fontSize: 16,
        color: "#0369a1",
        backgroundColor: "#e0f2fe",
        borderColor: "#bae6fd",
        borderWidth: 1,
        borderRadius: 8,
      },
      {
        id: "sticker_target",
        type: "sticker",
        x: 680,
        y: 410,
        width: 40,
        height: 40,
        rotation: 0,
        zIndex: 15,
        content: "🎯",
        fontSize: 30,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 60,
              y: 580,
              width: 670,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Habit & Goal Reflection",
              backgroundColor: "#f0f9ff",
              borderColor: "#e0f2fe",
              color: "#0369a1",
            },
          ]
        : []),
    ],
  },
  {
    id: "midnight_starlight",
    name: "Midnight Starlight",
    badge: "🌑",
    description: "Deep nocturnal midnight paper with golden constellations and moonlit thoughts.",
    paperStyle: "midnight_journal",
    paperColor: "#1E1F24",
    fontFamily: "Newsreader",
    generateElements: (title, date, text, aiSummary) => [
      {
        id: "tape_midnight",
        type: "tape",
        x: 320,
        y: 12,
        width: 150,
        height: 28,
        rotation: -1,
        zIndex: 5,
        tapeColor: "bg-amber-200/90 border-dashed border-amber-500",
      },
      {
        id: "entry_title",
        type: "text",
        x: 70,
        y: 60,
        width: 650,
        height: 60,
        rotation: 0,
        zIndex: 10,
        content: title || "Nocturne & Starlight",
        fontFamily: "Playfair Display",
        fontSize: 32,
        fontWeight: "bold",
        fontStyle: "italic",
        color: "#fef08a",
      },
      {
        id: "date_badge",
        type: "text",
        x: 70,
        y: 120,
        width: 250,
        height: 25,
        rotation: 0,
        zIndex: 10,
        content: `✨ Midnight Hour — ${date}`,
        fontFamily: "Courier Prime",
        fontSize: 13,
        color: "#93c5fd",
      },
      {
        id: "main_body",
        type: "text",
        x: 70,
        y: 160,
        width: 650,
        height: 420,
        rotation: 0,
        zIndex: 10,
        content: text || "Under the stillness of the midnight sky, thoughts untangle. The quiet creates space for truths that stay hidden by the glare of the day...",
        fontFamily: "Newsreader",
        fontSize: 18,
        color: "#f8fafc",
        textAlign: "left",
      },
      {
        id: "sticker_moon",
        type: "sticker",
        x: 670,
        y: 65,
        width: 45,
        height: 45,
        rotation: 12,
        zIndex: 15,
        content: "🌙",
        fontSize: 34,
      },
      {
        id: "sticker_stars",
        type: "sticker",
        x: 90,
        y: 590,
        width: 40,
        height: 40,
        rotation: -8,
        zIndex: 15,
        content: "✨",
        fontSize: 28,
      },
      ...(aiSummary
        ? [
            {
              id: "ai_insight_card",
              type: "ai_card" as const,
              x: 70,
              y: 640,
              width: 650,
              height: 120,
              rotation: 0,
              zIndex: 12,
              content: aiSummary,
              caption: "Nighttime Intuition",
              backgroundColor: "#2a2d36",
              borderColor: "#3f4452",
              color: "#e2e8f0",
            },
          ]
        : []),
    ],
  },
];
